[project]
name = "particle"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "nccapy",
    "wgpu",
    "pyside6",
    "numpy",
    "qtpy"]


[tool.uv]
link-mode = "symlink"
package = false
python-preference = "managed"

[tool.uv.workspace]
